[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
APP_ENV = "production"
APP_DEBUG = "false"
APP_NAME = "Srikandi Travel"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
FILESYSTEM_DISK = "local"
LOG_CHANNEL = "stack" 