[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=8000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_NAME = "Srikandi Travel"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
FILESYSTEM_DISK = "local"
LOG_CHANNEL = "stack"
NODE_ENV = "production" 